---

name: ci

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    name: test (${{ matrix.ruby }}, ${{ matrix.deps }})
    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    strategy:
      fail-fast: false

      matrix:
        ruby: [2.7.2, 2.6.6]
        os: [ubuntu-18.04]

        deps: [rails_52, rails_60, rails_61, rails_61_turbolinks, rails_61_webpacker]

        include:
          - ruby: 2.5.8
            os: ubuntu-18.04
            deps: rails_52

          - ruby: 2.5.8
            os: ubuntu-18.04
            deps: rails_60

          - ruby: 2.5.8
            os: ubuntu-18.04
            deps: rails_61

    env:
      COVERAGE: true

    steps:
      - uses: actions/checkout@v2

      - name: Configure bundler (default)
        run: |
          echo "BUNDLE_GEMFILE=Gemfile" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$(pwd)/vendor/bundle" >> $GITHUB_ENV
        if: matrix.deps == 'rails_61'

      - name: Configure bundler (alternative)
        run: |
          echo "BUNDLE_GEMFILE=gemfiles/${{ matrix.deps }}/Gemfile" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$(pwd)/gemfiles/${{ matrix.deps }}/vendor/bundle" >> $GITHUB_ENV
        if: matrix.deps != 'rails_61'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Install a specific rubygems version
        run: gem update --system 3.2.15

      - name: Install a specific bundler version
        run: gem install bundler -v 2.2.15

      - name: Cat current Gemfile to a specific file so caching works
        run: cat "$BUNDLE_GEMFILE.lock" > current_gemfile.lock

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: gems-${{ matrix.os }}-${{ matrix.ruby }}-${{ matrix.deps }}-${{ hashFiles('current_gemfile.lock') }}

      - name: Install dependencies
        run: bundle install

      - name: Setup git
        run: |
          git config --global user.email activeadmin@ci.dummy
          git config --global user.name ActiveAdmin

      - name: Create test app
        run: bin/rake setup

      - name: Restore cached RSpec runtimes
        uses: actions/cache@v2
        with:
          path: tmp/parallel_runtime_rspec.log
          key: runtimes-rspec-${{ matrix.ruby }}-${{ matrix.deps }}-${{ hashFiles('tmp/parallel_runtime_rspec.log') }}

      - name: Run RSpec tests
        run: |
          bin/parallel_rspec
          RSPEC_FILESYSTEM_CHANGES=true bin/rspec

      - name: Restore cached cucumber runtimes
        uses: actions/cache@v2
        with:
          path: tmp/parallel_runtime_cucumber.log
          key: runtimes-cucumber-${{ matrix.ruby }}-${{ matrix.deps }}-${{ hashFiles('tmp/parallel_runtime_cucumber.log') }}

      - name: Run Cucumber features
        run: |
          bin/parallel_cucumber --fail-fast
          bin/cucumber --profile filesystem-changes
          bin/cucumber --profile class-reloading

      - name: Format coverage
        run: |
          bin/prepare_coverage
          mv coverage/.resultset.json coverage/raw.${{ matrix.ruby }}.${{ matrix.deps }}.json

      - name: Save partial coverage as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/raw.${{ matrix.ruby }}.${{ matrix.deps }}.json
